### ISSUE TITLE
customElements.get(...) is undefined

### ISSUE THREAD

**Issue by tbowmo** [jimmy-landry/HA-Tablet-Dashboard-Config#10]
I get this error, when editing the left hand sidebar (just below the yaml code editor window). And am unable to save my changes

customElements.get(...) is undefined

**Comment by PH3601** [comment]
Hi, don't know how it works. But I had the same problem and solved it by going to another dashboard and crating a new card(Custom: Vertical Stack In Card) → added something random → then I went back to the original dashboard and refreshed the browser and then it worked. 
Could be worth a try...

**Comment by pjaer** [comment]
> Hi, don't know how it works. But I had the same problem and solved it by going to another dashboard and crating a new card(Custom: Vertical Stack In Card) → added something random → then I went back to the original dashboard (don't refresh the browser) and then it worked. Could be worth a try...
> 
> *after refreshing the browser, I need to redo the steps. But the config gets saved

Wow, really insane. I had another error showing up when I was editing the sidebar panel in code mode, it said:

```
Configuration error:
Cannot read properties of undefined (reading 'getConfigElement')
```

Your answer truly fixed that. Apparently I'd been coding in non-visual mode uneccesarily but after this hack I could edit each section/card in visual mode again. Thanks! :tada:

**Comment by jimmy-landry** [comment]
HA is so weird sometimes...thanks ph3601 for the fix!
