### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by killervette42** [jimmy-landry/HA-Tablet-Dashboard-Config#2]
Can you help me get your theme running? I wasn't really sure how to start, so I went to matt8707 page and installed his theme first. I replace his theme file with you tablet.yaml, but it isn't working out. My default overview dashboard has "set theme to tablet in profile" in giant yellow, but I have enabled the theme. the sidebar doesn't have anything like you theme. All the button cards are still in matt8707's language.  the media card says "custom element doesn't exist: swipe card".  Not sure where to start.

**Comment by killervette42** [comment]
I got a bit further but the left sidebar errors and says custom element doesn’t exist:vertical-stack-in-card. I did install that in hacs

**Comment by jimmy-landry** [comment]
If the buttons are still in matt8707's language you may have imported the wrong file. Go to Settings > Dashboards and create a new dashboard from scratch. Open the raw config editor and delete anything that's there, then paste in the yaml file (wall_tablet_grid_redacted.yaml) from this repo. This should fix a lot of the issues.

As for the vertical stack-in card, it's a little bit buggy when it comes to how to specify the card type. Try putting the card type in single or double quotes if you haven't already, like this:
```
'custom:vertical-stack-in-card'
```

**Comment by rymiller11** [comment]
I'm getting the same issue with custom element doesn't exist.  Here the line it says doesn't exist:

type: "custom:grid-layout"

Tried this with single and double quotes.  After checking after saving it appears the quotes are not saved.

**Comment by rymiller11** [comment]
Resolved:  not sure exactly how but there must be some other component that I installed that had the grid-layout within it.

**Comment by jimmy-landry** [comment]
👍
